const SongTypes = {
  FETCH_SONG_REQUEST: "FETCH_SONG_REQUEST",
  FETCH_SONG_ERROR: "FETCH_SONG_ERROR",
  FETCH_SONG_SUCCESS: "FETCH_SONG_SUCCESS",
  SONG_UPDATING: "RECIPE_UPDATING",
  SONG_UPDATING_ERROR: "RECIPE_UPDATING_ERROR",
  ADD_SONG_LIKE: "ADD_SONG_LIKE",
  REMOVE_SONG_LIKE: "REMOVE_SONG_LIKE",
};

export default SongTypes;
