const UserTypes = {
  FORM_REQUEST: "FORM_REQUEST",
  FORM_ERROR: "FORM_ERROR",
  FORM_SUCCESS: "FORM_SUCCESS",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_ERROR: "SIGNUP_ERROR",
  SIGNOUT_REQUEST: "SIGNOUT_REQUEST",
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
  SIGNOUT_ERROR: "SIGNOUT_ERROR",
  UPDATE_LOCATION_REQUEST : "UPDATE_LOCATION_REQUEST",
  UPDATE_LOCATION_SUCCESS : "UPDATE_LOCATION_SUCCESS",
  UPDATE_LOCATION_ERROR : "UPDATE_LOCATION_ERROR",
  UPDATE_LIKE_REQUEST : "UPDATE_LIKE_REQUEST",
  UPDATE_LIKE_SUCCESS : "UPDATE_LIKE_SUCCESS",
  UPDATE_LIKE_ERROR : "UPDATE_LIKE_ERROR",
};

export default UserTypes;
