const CommunityTypes = {
  FETCH_NEAR_PEOPLE: "FETCH_NEAR_PEOPLE",
  FETCH_NEAR_PEOPLE_ERROR: "FETCH_NEAR_PEOPLE_ERROR",
  FETCH_NEAR_PEOPLE_SUCCESS: "FETCH_NEAR_PEOPLE_SUCCESS",
  GET_PROFILE_REQUEST : "GET_PROFILE_REQUEST",
  GET_PROFILE_SUCCESS : "GET_PROFILE_SUCCESS",
  GET_PROFILE_ERROR : "GET_PROFILE_ERROR",
  GET_CHATS_REQUEST: "GET_CHATS_REQUEST",
  GET_CHATS_SUCCESS: "GET_CHATS_SUCCESS",
  GET_CHATS_ERROR: "GET_CHATS_ERROR",
  OPEN_CHAT_ROOM_REQUEST: "OPEN_CHAT_ROOM_REQUEST",
  OPEN_CHAT_ROOM_SUCCESS: "OPEN_CHAT_ROOM_SUCCESS",
  OPEN_CHAT_ROOM_ERROR: "OPEN_CHAT_ROOM_ERROR",
};

export default CommunityTypes;
